package api

// Languages is the list of supported target languages.
var Languages = []Language{
	{Code: "af", Name: "Afrikaans"},
	{Code: "sq", Name: "Albanian"},
	{Code: "am", Name: "Amharic"},
	{Code: "ar", Name: "Arabic"},
	{Code: "hy", Name: "Armenian"},
	{Code: "az", Name: "Azerbaijani"},
	{Code: "eu", Name: "Basque"},
	{Code: "be", Name: "Belarusian"},
	{Code: "bn", Name: "Bengali"},
	{Code: "bs", Name: "Bosnian"},
	{Code: "bg", Name: "Bulgarian"},
	{Code: "my", Name: "Burmese"},
	{Code: "ca", Name: "Catalan"},
	{Code: "zh", Name: "Chinese"},
	{Code: "hr", Name: "Croatian"},
	{Code: "cs", Name: "Czech"},
	{Code: "da", Name: "Danish"},
	{Code: "nl", Name: "Dutch"},
	{Code: "et", Name: "Estonian"},
	{Code: "fi", Name: "Finnish"},
	{Code: "fr", Name: "French"},
	{Code: "ka", Name: "Georgian"},
	{Code: "de", Name: "German"},
	{Code: "el", Name: "Greek"},
	{Code: "gu", Name: "Gujarati"},
	{Code: "ht", Name: "Haitian Creole"},
	{Code: "ha", Name: "Hausa"},
	{Code: "he", Name: "Hebrew"},
	{Code: "hi", Name: "Hindi"},
	{Code: "hu", Name: "Hungarian"},
	{Code: "is", Name: "Icelandic"},
	{Code: "ig", Name: "Igbo"},
	{Code: "id", Name: "Indonesian"},
	{Code: "ga", Name: "Irish"},
	{Code: "it", Name: "Italian"},
	{Code: "ja", Name: "Japanese"},
	{Code: "jv", Name: "Javanese"},
	{Code: "kn", Name: "Kannada"},
	{Code: "kk", Name: "Kazakh"},
	{Code: "km", Name: "Khmer"},
	{Code: "ko", Name: "Korean"},
	{Code: "ku", Name: "Kurdish"},
	{Code: "lo", Name: "Lao"},
	{Code: "lv", Name: "Latvian"},
	{Code: "lt", Name: "Lithuanian"},
	{Code: "mk", Name: "Macedonian"},
	{Code: "ms", Name: "Malay"},
	{Code: "ml", Name: "Malayalam"},
	{Code: "mt", Name: "Maltese"},
	{Code: "mi", Name: "Maori"},
	{Code: "mr", Name: "Marathi"},
	{Code: "mn", Name: "Mongolian"},
	{Code: "ne", Name: "Nepali"},
	{Code: "no", Name: "Norwegian"},
	{Code: "ps", Name: "Pashto"},
	{Code: "fa", Name: "Persian"},
	{Code: "pl", Name: "Polish"},
	{Code: "pt", Name: "Portuguese"},
	{Code: "pa", Name: "Punjabi"},
	{Code: "ro", Name: "Romanian"},
	{Code: "ru", Name: "Russian"},
	{Code: "sr", Name: "Serbian"},
	{Code: "si", Name: "Sinhala"},
	{Code: "sk", Name: "Slovak"},
	{Code: "sl", Name: "Slovenian"},
	{Code: "so", Name: "Somali"},
	{Code: "es", Name: "Spanish"},
	{Code: "sw", Name: "Swahili"},
	{Code: "sv", Name: "Swedish"},
	{Code: "tl", Name: "Tagalog"},
	{Code: "ta", Name: "Tamil"},
	{Code: "te", Name: "Telugu"},
	{Code: "th", Name: "Thai"},
	{Code: "tr", Name: "Turkish"},
	{Code: "uk", Name: "Ukrainian"},
	{Code: "ur", Name: "Urdu"},
	{Code: "uz", Name: "Uzbek"},
	{Code: "vi", Name: "Vietnamese"},
	{Code: "cy", Name: "Welsh"},
	{Code: "yo", Name: "Yoruba"},
	{Code: "zu", Name: "Zulu"},
}

// PopularLanguages is a subset shown by default in selection UIs.
var PopularLanguages = []Language{
	{Code: "es", Name: "Spanish"},
	{Code: "fr", Name: "French"},
	{Code: "de", Name: "German"},
	{Code: "ja", Name: "Japanese"},
	{Code: "it", Name: "Italian"},
	{Code: "pt", Name: "Portuguese"},
	{Code: "ko", Name: "Korean"},
	{Code: "zh", Name: "Chinese"},
}

// LanguageByCode returns a language by its code, or nil if not found.
func LanguageByCode(code string) *Language {
	for i := range Languages {
		if Languages[i].Code == code {
			return &Languages[i]
		}
	}
	return nil
}
